// AUTO-GENERATED by scripts/sync-box-editor-data.py - do not edit by hand.
// Run `python scripts/sync-box-editor-data.py` after changing
// docs/box-schema/*.schema.json or the bundled examples.
window.CSBDATA = {
  "schemas": {
    "box": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://csgobox.reclizer.com/schemas/box.schema.json",
      "title": "CS2-Box Box Definition",
      "description": "Schema for a CS2-Box crate / terminal definition (config/csbox/<id>.json). The file name (minus .json) becomes the box id. Terminal prices are NOT part of box files anymore — they live in the central price table config/csbox/_prices.json (see prices.schema.json); a leftover 'price' field is rejected by the runtime validator. Runtime validation in-game is authoritative; this schema is an authoring aid for IDE autocomplete / offline checks.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Display name shown on the box item and GUI. May start with a '#RRGGBB ' color prefix (e.g. \"#FF5555 神化宝石箱\")."
        },
        "type": {
          "type": "string",
          "enum": [
            "csbox",
            "terminal"
          ],
          "description": "csbox = regular crate (default), terminal = terminal machine. Terminals must NOT declare a key field."
        },
        "key": {
          "type": "string",
          "description": "Key item id required to open. Use minecraft:air for a keyless box. Terminals forbid this field."
        },
        "drop": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0,
          "description": "Default entity drop chance (0.0-1.0)."
        },
        "random": {
          "type": "array",
          "minItems": 5,
          "maxItems": 5,
          "items": {
            "type": "integer",
            "minimum": 0,
            "maximum": 10000
          },
          "description": "Five grade weights ordered grade1(common)..grade5(rare). Non-positive uses defaults; >10000 clamps."
        },
        "entity": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0
              }
            ]
          },
          "description": "Entity ids that drop this box, or alternating id/rate pairs."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "v2.0.1: false skips this box entirely (no error)."
        },
        "requires": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "v2.0.1: list of mod ids that must be loaded; the box is skipped with an error when any is missing."
        },
        "icon": {
          "oneOf": [
            {
              "type": "string",
              "description": "Item-model id (26.x renders directly; other versions warn)"
            },
            {
              "type": "integer",
              "minimum": 0,
              "description": "CustomModelData value (pair with a resource pack)"
            }
          ],
          "description": "v2.0.1: per-box icon override."
        },
        "discount": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0,
          "default": 0.0,
          "description": "v2.0.1: terminal price discount (0..1 off), e.g. 0.2 = 20% off."
        },
        "stock": {
          "type": "integer",
          "minimum": -1,
          "default": -1,
          "description": "v2.0.1: terminal stock limit; -1 = unlimited."
        },
        "format_version": {
          "type": "integer",
          "minimum": 1,
          "description": "v2.0.2: config schema version marker. Optional today (absent = legacy); write 2 for current files. Unknown top-level/item fields are reported by the runtime validator, so version bumps should add themselves here."
        },
        "max_per_player": {
          "type": "integer",
          "minimum": -1,
          "default": -1,
          "description": "v2.0.1: per-player open cap; -1 = unlimited (in-memory, resets on restart)."
        },
        "cooldown_seconds": {
          "type": "integer",
          "minimum": 0,
          "default": 0,
          "description": "v2.0.1: per-box open cooldown; 0 = none."
        },
        "permission": {
          "type": "string",
          "description": "v2.0.1: permission node checked against the PERMISSION_GATE hook (default allow-all)."
        },
        "pity": {
          "type": "object",
          "properties": {
            "grade": {
              "type": "string",
              "enum": [
                "consumer",
                "industrial",
                "mil_spec",
                "restricted",
                "classified"
              ],
              "description": "v2.0.1: the grade that must eventually drop; forces a roll at/above it."
            },
            "every": {
              "type": "integer",
              "minimum": 2,
              "description": "v2.0.1: after every-1 consecutive opens below the target grade, the next open is forced to roll the target grade or higher. In-memory per player+box, resets on restart."
            }
          },
          "required": [
            "grade",
            "every"
          ],
          "additionalProperties": false,
          "description": "v2.0.1: pity (保底) policy. Invalid grade ids or every < 2 degrade to no pity (schema validator reports the mistake)."
        },
        "grade1": {
          "$ref": "#/$defs/grade"
        },
        "grade2": {
          "$ref": "#/$defs/grade"
        },
        "grade3": {
          "$ref": "#/$defs/grade"
        },
        "grade4": {
          "$ref": "#/$defs/grade"
        },
        "grade5": {
          "$ref": "#/$defs/grade"
        }
      },
      "$defs": {
        "grade": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/item"
          },
          "description": "Items in this grade tier (grade1 lowest rarity .. grade5 highest)."
        },
        "item": {
          "type": "object",
          "description": "One item pool entry. Exactly one source: id, '#tag' or loot_table. Terminal prices come from the central _prices.json table, never from this object.",
          "properties": {
            "id": {
              "type": "string",
              "description": "Item registry id, e.g. minecraft:diamond_sword."
            },
            "tag": {
              "type": "string",
              "description": "Dual-purpose (matches runtime BoxItemCodec): a string starting with '#' is an item tag reference expanded at load time (e.g. '#minecraft:swords'); any other value is parsed as an SNBT string applied to the stack (e.g. '{GunId:\"tacz:modern_kinetics_gun_57\"}')."
            },
            "loot_table": {
              "type": "string",
              "description": "Loot table reference, e.g. minecraft:chests/simple_dungeon. Rolled at open time."
            },
            "count": {
              "oneOf": [
                {
                  "type": "integer",
                  "minimum": 1
                },
                {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": {
                    "type": "integer",
                    "minimum": 1
                  }
                }
              ],
              "description": "Item count, or [min,max] rolled at open time (v2.0.1)."
            },
            "weight": {
              "type": "integer",
              "minimum": 0,
              "default": 1,
              "description": "v2.0.1: intra-grade weight; 0 disables the entry."
            },
            "enchant": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Enchantment id, e.g. minecraft:sharpness"
                    },
                    "level": {
                      "oneOf": [
                        {
                          "type": "integer",
                          "minimum": 1
                        },
                        {
                          "type": "array",
                          "minItems": 2,
                          "maxItems": 2,
                          "items": {
                            "type": "integer",
                            "minimum": 1
                          }
                        }
                      ],
                      "description": "Fixed level or [min,max] range."
                    }
                  },
                  "additionalProperties": false
                }
              ],
              "description": "v2.0.1: random-enchant shortcut (true = any enchant, or {id, level})."
            },
            "price": {
              "not": {},
              "description": "REMOVED — do not use. Terminal prices are centrally managed in config/csbox/_prices.json (see prices.schema.json). A leftover price here is reported by the in-game validator; the item is treated as unpriced (terminal never sells it, recycler pays 0) until migrated."
            },
            "components": {
              "type": "object",
              "description": "Data components (1.21+/26.x). Ignored on 1.20.1."
            }
          },
          "oneOf": [
            {
              "required": [
                "id"
              ]
            },
            {
              "required": [
                "tag"
              ]
            },
            {
              "required": [
                "loot_table"
              ]
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "prices": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://csgobox.reclizer.com/schemas/prices.schema.json",
      "title": "CS2-Box Price Table",
      "description": "Central terminal price table (config/csbox/_prices.json). Keys are item registry ids ('minecraft:diamond_sword') or id#variant sub-keys for NBT-distinguished items ('tacz:modern_kinetic_gun#tacz:deagle_golden'); values are a fixed non-negative integer ('200') or an inclusive random range '[min, max]' ('[1500, 3000]', same style as the count interval) in Armory Points — ranges are sampled once per terminal offer / recycle. Items without an entry have NO price: terminals never offer them, the recycler pays 0, and boxes containing unpriced id entries refuse to load (loot_table entries are the only exception and are never offered). The underscore prefix keeps the file out of the box scan.",
      "type": "object",
      "propertyNames": {
        "pattern": "^[a-z0-9_.-]+:[a-z0-9_./-]+(#.+)?$"
      },
      "additionalProperties": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 0,
            "description": "Fixed terminal purchase price in Armory Points for the item id (or id#variant)."
          },
          {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer",
              "minimum": 0
            },
            "description": "Random price range [min, max] (inclusive) in Armory Points; sampled once per terminal offer (and per recycle). min must not exceed max (reported at runtime)."
          }
        ]
      }
    }
  },
  "versions": [
    {
      "key": "1.21.1",
      "label": {
        "en": "1.21.1 (NeoForge)",
        "zh": "1.21.1 (NeoForge)"
      },
      "short": {
        "en": "1.21.1",
        "zh": "1.21.1"
      },
      "taczVariants": true,
      "components": true,
      "itemModel": false,
      "note": {
        "en": "Data Components; TACZ GunId/AmmoId variants supported.",
        "zh": "Data Components；支持 TACZ GunId/AmmoId 变体键。"
      }
    },
    {
      "key": "26.1.2",
      "label": {
        "en": "26.1.2",
        "zh": "26.1.2"
      },
      "short": {
        "en": "26.1.2",
        "zh": "26.1.2"
      },
      "taczVariants": false,
      "components": true,
      "itemModel": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "26.2",
      "label": {
        "en": "26.2",
        "zh": "26.2"
      },
      "short": {
        "en": "26.2",
        "zh": "26.2"
      },
      "taczVariants": false,
      "components": true,
      "itemModel": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "forge-26.1.2",
      "label": {
        "en": "Forge 26.1.2",
        "zh": "Forge 26.1.2"
      },
      "short": {
        "en": "Forge 26.1.2",
        "zh": "Forge 26.1.2"
      },
      "taczVariants": false,
      "components": true,
      "itemModel": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "forge-26.2",
      "label": {
        "en": "Forge 26.2",
        "zh": "Forge 26.2"
      },
      "short": {
        "en": "Forge 26.2",
        "zh": "Forge 26.2"
      },
      "taczVariants": false,
      "components": true,
      "itemModel": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "forge-1.20.1",
      "label": {
        "en": "Forge 1.20.1",
        "zh": "Forge 1.20.1"
      },
      "short": {
        "en": "Forge 1.20.1",
        "zh": "Forge 1.20.1"
      },
      "taczVariants": true,
      "components": false,
      "itemModel": false,
      "note": {
        "en": "Legacy NBT tag (no Data Components); TACZ variants supported.",
        "zh": "旧版 NBT tag（无 Data Components）；支持 TACZ 变体键。"
      }
    }
  ],
  "gradeNames": [
    {
      "id": "consumer",
      "zh": "消费级（灰）",
      "en": "Consumer (Gray)"
    },
    {
      "id": "industrial",
      "zh": "工业级（浅蓝）",
      "en": "Industrial (Light Blue)"
    },
    {
      "id": "mil_spec",
      "zh": "军规级（蓝）",
      "en": "Mil-Spec (Blue)"
    },
    {
      "id": "restricted",
      "zh": "受限级（紫）",
      "en": "Restricted (Purple)"
    },
    {
      "id": "classified",
      "zh": "保密级（粉/红）",
      "en": "Classified (Pink/Red)"
    }
  ],
  "gradeDefaultPrices": [
    6,
    10,
    16,
    22,
    30
  ],
  "gradeRecycleYields": [
    3,
    5,
    7,
    8,
    8
  ],
  "keySuggestions": [
    {
      "id": "minecraft:air",
      "en": "Keyless (minecraft:air)",
      "zh": "免钥匙 (minecraft:air)"
    },
    {
      "id": "csgobox:csgo_key_copper",
      "en": "Copper Key",
      "zh": "铜钥匙"
    },
    {
      "id": "csgobox:csgo_key0",
      "en": "Iron Key",
      "zh": "铁钥匙"
    },
    {
      "id": "csgobox:csgo_key1",
      "en": "Gold Key",
      "zh": "金钥匙"
    },
    {
      "id": "csgobox:csgo_key2",
      "en": "Diamond Key",
      "zh": "钻石钥匙"
    },
    {
      "id": "csgobox:csgo_key3",
      "en": "Netherite Key",
      "zh": "下界合金钥匙"
    }
  ],
  "entitySuggestions": [
    {
      "id": "allay",
      "en": "Allay",
      "zh": "悦灵"
    },
    {
      "id": "armadillo",
      "en": "Armadillo",
      "zh": "犰狳"
    },
    {
      "id": "axolotl",
      "en": "Axolotl",
      "zh": "美西螈"
    },
    {
      "id": "bat",
      "en": "Bat",
      "zh": "蝙蝠"
    },
    {
      "id": "bee",
      "en": "Bee",
      "zh": "蜜蜂"
    },
    {
      "id": "blaze",
      "en": "Blaze",
      "zh": "烈焰人"
    },
    {
      "id": "bogged",
      "en": "Bogged",
      "zh": "沼泽骷髅"
    },
    {
      "id": "breeze",
      "en": "Breeze",
      "zh": "旋风人"
    },
    {
      "id": "camel",
      "en": "Camel",
      "zh": "骆驼"
    },
    {
      "id": "cat",
      "en": "Cat",
      "zh": "猫"
    },
    {
      "id": "cave_spider",
      "en": "Cave Spider",
      "zh": "洞穴蜘蛛"
    },
    {
      "id": "chicken",
      "en": "Chicken",
      "zh": "鸡"
    },
    {
      "id": "cod",
      "en": "Cod",
      "zh": "鳕鱼"
    },
    {
      "id": "cow",
      "en": "Cow",
      "zh": "牛"
    },
    {
      "id": "creeper",
      "en": "Creeper",
      "zh": "苦力怕"
    },
    {
      "id": "dolphin",
      "en": "Dolphin",
      "zh": "海豚"
    },
    {
      "id": "donkey",
      "en": "Donkey",
      "zh": "驴"
    },
    {
      "id": "drowned",
      "en": "Drowned",
      "zh": "溺尸"
    },
    {
      "id": "elder_guardian",
      "en": "Elder Guardian",
      "zh": "远古守卫者"
    },
    {
      "id": "ender_dragon",
      "en": "Ender Dragon",
      "zh": "末影龙"
    },
    {
      "id": "enderman",
      "en": "Enderman",
      "zh": "末影人"
    },
    {
      "id": "endermite",
      "en": "Endermite",
      "zh": "末影螨"
    },
    {
      "id": "evoker",
      "en": "Evoker",
      "zh": "唤魔者"
    },
    {
      "id": "fox",
      "en": "Fox",
      "zh": "狐狸"
    },
    {
      "id": "frog",
      "en": "Frog",
      "zh": "青蛙"
    },
    {
      "id": "ghast",
      "en": "Ghast",
      "zh": "恶魂"
    },
    {
      "id": "glow_squid",
      "en": "Glow Squid",
      "zh": "发光鱿鱼"
    },
    {
      "id": "goat",
      "en": "Goat",
      "zh": "山羊"
    },
    {
      "id": "guardian",
      "en": "Guardian",
      "zh": "守卫者"
    },
    {
      "id": "hoglin",
      "en": "Hoglin",
      "zh": "疣猪兽"
    },
    {
      "id": "horse",
      "en": "Horse",
      "zh": "马"
    },
    {
      "id": "husk",
      "en": "Husk",
      "zh": "尸壳"
    },
    {
      "id": "iron_golem",
      "en": "Iron Golem",
      "zh": "铁傀儡"
    },
    {
      "id": "llama",
      "en": "Llama",
      "zh": "羊驼"
    },
    {
      "id": "magma_cube",
      "en": "Magma Cube",
      "zh": "岩浆怪"
    },
    {
      "id": "mooshroom",
      "en": "Mooshroom",
      "zh": "哞菇"
    },
    {
      "id": "mule",
      "en": "Mule",
      "zh": "骡"
    },
    {
      "id": "ocelot",
      "en": "Ocelot",
      "zh": "豹猫"
    },
    {
      "id": "panda",
      "en": "Panda",
      "zh": "熊猫"
    },
    {
      "id": "parrot",
      "en": "Parrot",
      "zh": "鹦鹉"
    },
    {
      "id": "phantom",
      "en": "Phantom",
      "zh": "幻翼"
    },
    {
      "id": "pig",
      "en": "Pig",
      "zh": "猪"
    },
    {
      "id": "piglin",
      "en": "Piglin",
      "zh": "猪灵"
    },
    {
      "id": "piglin_brute",
      "en": "Piglin Brute",
      "zh": "猪灵蛮兵"
    },
    {
      "id": "pillager",
      "en": "Pillager",
      "zh": "掠夺者"
    },
    {
      "id": "polar_bear",
      "en": "Polar Bear",
      "zh": "北极熊"
    },
    {
      "id": "pufferfish",
      "en": "Pufferfish",
      "zh": "河豚"
    },
    {
      "id": "rabbit",
      "en": "Rabbit",
      "zh": "兔子"
    },
    {
      "id": "ravager",
      "en": "Ravager",
      "zh": "劫掠兽"
    },
    {
      "id": "salmon",
      "en": "Salmon",
      "zh": "鲑鱼"
    },
    {
      "id": "sheep",
      "en": "Sheep",
      "zh": "绵羊"
    },
    {
      "id": "shulker",
      "en": "Shulker",
      "zh": "潜影贝"
    },
    {
      "id": "silverfish",
      "en": "Silverfish",
      "zh": "蠹虫"
    },
    {
      "id": "skeleton",
      "en": "Skeleton",
      "zh": "骷髅"
    },
    {
      "id": "skeleton_horse",
      "en": "Skeleton Horse",
      "zh": "骷髅马"
    },
    {
      "id": "slime",
      "en": "Slime",
      "zh": "史莱姆"
    },
    {
      "id": "sniffer",
      "en": "Sniffer",
      "zh": "嗅探兽"
    },
    {
      "id": "snow_golem",
      "en": "Snow Golem",
      "zh": "雪傀儡"
    },
    {
      "id": "spider",
      "en": "Spider",
      "zh": "蜘蛛"
    },
    {
      "id": "squid",
      "en": "Squid",
      "zh": "鱿鱼"
    },
    {
      "id": "stray",
      "en": "Stray",
      "zh": "流浪者"
    },
    {
      "id": "strider",
      "en": "Strider",
      "zh": "炽足兽"
    },
    {
      "id": "tadpole",
      "en": "Tadpole",
      "zh": "蝌蚪"
    },
    {
      "id": "trader_llama",
      "en": "Trader Llama",
      "zh": "行商羊驼"
    },
    {
      "id": "tropical_fish",
      "en": "Tropical Fish",
      "zh": "热带鱼"
    },
    {
      "id": "turtle",
      "en": "Turtle",
      "zh": "海龟"
    },
    {
      "id": "vex",
      "en": "Vex",
      "zh": "恼鬼"
    },
    {
      "id": "villager",
      "en": "Villager",
      "zh": "村民"
    },
    {
      "id": "vindicator",
      "en": "Vindicator",
      "zh": "卫道士"
    },
    {
      "id": "wandering_trader",
      "en": "Wandering Trader",
      "zh": "流浪商人"
    },
    {
      "id": "warden",
      "en": "Warden",
      "zh": "循声守卫"
    },
    {
      "id": "witch",
      "en": "Witch",
      "zh": "女巫"
    },
    {
      "id": "wither",
      "en": "Wither",
      "zh": "凋灵"
    },
    {
      "id": "wither_skeleton",
      "en": "Wither Skeleton",
      "zh": "凋灵骷髅"
    },
    {
      "id": "wolf",
      "en": "Wolf",
      "zh": "狼"
    },
    {
      "id": "zoglin",
      "en": "Zoglin",
      "zh": "僵尸疣猪兽"
    },
    {
      "id": "zombie",
      "en": "Zombie",
      "zh": "僵尸"
    },
    {
      "id": "zombie_horse",
      "en": "Zombie Horse",
      "zh": "僵尸马"
    },
    {
      "id": "zombie_villager",
      "en": "Zombie Villager",
      "zh": "僵尸村民"
    }
  ],
  "itemSuggestions": [
    {
      "id": "wooden_sword",
      "en": "Wooden Sword",
      "zh": "木剑"
    },
    {
      "id": "stone_sword",
      "en": "Stone Sword",
      "zh": "石剑"
    },
    {
      "id": "iron_sword",
      "en": "Iron Sword",
      "zh": "铁剑"
    },
    {
      "id": "golden_sword",
      "en": "Golden Sword",
      "zh": "金剑"
    },
    {
      "id": "diamond_sword",
      "en": "Diamond Sword",
      "zh": "钻石剑"
    },
    {
      "id": "netherite_sword",
      "en": "Netherite Sword",
      "zh": "下界合金剑"
    },
    {
      "id": "wooden_axe",
      "en": "Wooden Axe",
      "zh": "木斧"
    },
    {
      "id": "stone_axe",
      "en": "Stone Axe",
      "zh": "石斧"
    },
    {
      "id": "iron_axe",
      "en": "Iron Axe",
      "zh": "铁斧"
    },
    {
      "id": "golden_axe",
      "en": "Golden Axe",
      "zh": "金斧"
    },
    {
      "id": "diamond_axe",
      "en": "Diamond Axe",
      "zh": "钻石斧"
    },
    {
      "id": "netherite_axe",
      "en": "Netherite Axe",
      "zh": "下界合金斧"
    },
    {
      "id": "trident",
      "en": "Trident",
      "zh": "三叉戟"
    },
    {
      "id": "mace",
      "en": "Mace",
      "zh": "重锤"
    },
    {
      "id": "bow",
      "en": "Bow",
      "zh": "弓"
    },
    {
      "id": "crossbow",
      "en": "Crossbow",
      "zh": "弩"
    },
    {
      "id": "arrow",
      "en": "Arrow",
      "zh": "箭"
    },
    {
      "id": "tipped_arrow",
      "en": "Tipped Arrow",
      "zh": "药水箭"
    },
    {
      "id": "spectral_arrow",
      "en": "Spectral Arrow",
      "zh": "光灵箭"
    },
    {
      "id": "shield",
      "en": "Shield",
      "zh": "盾牌"
    },
    {
      "id": "wooden_pickaxe",
      "en": "Wooden Pickaxe",
      "zh": "木镐"
    },
    {
      "id": "stone_pickaxe",
      "en": "Stone Pickaxe",
      "zh": "石镐"
    },
    {
      "id": "iron_pickaxe",
      "en": "Iron Pickaxe",
      "zh": "铁镐"
    },
    {
      "id": "golden_pickaxe",
      "en": "Golden Pickaxe",
      "zh": "金镐"
    },
    {
      "id": "diamond_pickaxe",
      "en": "Diamond Pickaxe",
      "zh": "钻石镐"
    },
    {
      "id": "netherite_pickaxe",
      "en": "Netherite Pickaxe",
      "zh": "下界合金镐"
    },
    {
      "id": "iron_shovel",
      "en": "Iron Shovel",
      "zh": "铁锹"
    },
    {
      "id": "diamond_shovel",
      "en": "Diamond Shovel",
      "zh": "钻石锹"
    },
    {
      "id": "netherite_shovel",
      "en": "Netherite Shovel",
      "zh": "下界合金锹"
    },
    {
      "id": "iron_hoe",
      "en": "Iron Hoe",
      "zh": "铁锄"
    },
    {
      "id": "diamond_hoe",
      "en": "Diamond Hoe",
      "zh": "钻石锄"
    },
    {
      "id": "shears",
      "en": "Shears",
      "zh": "剪刀"
    },
    {
      "id": "flint_and_steel",
      "en": "Flint and Steel",
      "zh": "打火石"
    },
    {
      "id": "fishing_rod",
      "en": "Fishing Rod",
      "zh": "钓鱼竿"
    },
    {
      "id": "compass",
      "en": "Compass",
      "zh": "指南针"
    },
    {
      "id": "clock",
      "en": "Clock",
      "zh": "时钟"
    },
    {
      "id": "spyglass",
      "en": "Spyglass",
      "zh": "望远镜"
    },
    {
      "id": "brush",
      "en": "Brush",
      "zh": "刷子"
    },
    {
      "id": "lead",
      "en": "Lead",
      "zh": "拴绳"
    },
    {
      "id": "name_tag",
      "en": "Name Tag",
      "zh": "命名牌"
    },
    {
      "id": "saddle",
      "en": "Saddle",
      "zh": "鞍"
    },
    {
      "id": "leather_helmet",
      "en": "Leather Helmet",
      "zh": "皮革头盔"
    },
    {
      "id": "leather_chestplate",
      "en": "Leather Chestplate",
      "zh": "皮革胸甲"
    },
    {
      "id": "leather_leggings",
      "en": "Leather Leggings",
      "zh": "皮革裤子"
    },
    {
      "id": "leather_boots",
      "en": "Leather Boots",
      "zh": "皮革靴子"
    },
    {
      "id": "chainmail_helmet",
      "en": "Chainmail Helmet",
      "zh": "锁链头盔"
    },
    {
      "id": "chainmail_chestplate",
      "en": "Chainmail Chestplate",
      "zh": "锁链胸甲"
    },
    {
      "id": "chainmail_leggings",
      "en": "Chainmail Leggings",
      "zh": "锁链裤子"
    },
    {
      "id": "chainmail_boots",
      "en": "Chainmail Boots",
      "zh": "锁链靴子"
    },
    {
      "id": "iron_helmet",
      "en": "Iron Helmet",
      "zh": "铁头盔"
    },
    {
      "id": "iron_chestplate",
      "en": "Iron Chestplate",
      "zh": "铁胸甲"
    },
    {
      "id": "iron_leggings",
      "en": "Iron Leggings",
      "zh": "铁裤子"
    },
    {
      "id": "iron_boots",
      "en": "Iron Boots",
      "zh": "铁靴子"
    },
    {
      "id": "golden_helmet",
      "en": "Golden Helmet",
      "zh": "金头盔"
    },
    {
      "id": "golden_chestplate",
      "en": "Golden Chestplate",
      "zh": "金胸甲"
    },
    {
      "id": "golden_leggings",
      "en": "Golden Leggings",
      "zh": "金裤子"
    },
    {
      "id": "golden_boots",
      "en": "Golden Boots",
      "zh": "金靴子"
    },
    {
      "id": "diamond_helmet",
      "en": "Diamond Helmet",
      "zh": "钻石头盔"
    },
    {
      "id": "diamond_chestplate",
      "en": "Diamond Chestplate",
      "zh": "钻石胸甲"
    },
    {
      "id": "diamond_leggings",
      "en": "Diamond Leggings",
      "zh": "钻石裤子"
    },
    {
      "id": "diamond_boots",
      "en": "Diamond Boots",
      "zh": "钻石靴子"
    },
    {
      "id": "netherite_helmet",
      "en": "Netherite Helmet",
      "zh": "下界合金头盔"
    },
    {
      "id": "netherite_chestplate",
      "en": "Netherite Chestplate",
      "zh": "下界合金胸甲"
    },
    {
      "id": "netherite_leggings",
      "en": "Netherite Leggings",
      "zh": "下界合金裤子"
    },
    {
      "id": "netherite_boots",
      "en": "Netherite Boots",
      "zh": "下界合金靴子"
    },
    {
      "id": "turtle_helmet",
      "en": "Turtle Shell",
      "zh": "海龟壳"
    },
    {
      "id": "elytra",
      "en": "Elytra",
      "zh": "鞘翅"
    },
    {
      "id": "coal",
      "en": "Coal",
      "zh": "煤炭"
    },
    {
      "id": "charcoal",
      "en": "Charcoal",
      "zh": "木炭"
    },
    {
      "id": "raw_iron",
      "en": "Raw Iron",
      "zh": "粗铁"
    },
    {
      "id": "raw_gold",
      "en": "Raw Gold",
      "zh": "粗金"
    },
    {
      "id": "raw_copper",
      "en": "Raw Copper",
      "zh": "粗铜"
    },
    {
      "id": "iron_ingot",
      "en": "Iron Ingot",
      "zh": "铁锭"
    },
    {
      "id": "gold_ingot",
      "en": "Gold Ingot",
      "zh": "金锭"
    },
    {
      "id": "copper_ingot",
      "en": "Copper Ingot",
      "zh": "铜锭"
    },
    {
      "id": "netherite_ingot",
      "en": "Netherite Ingot",
      "zh": "下界合金锭"
    },
    {
      "id": "netherite_scrap",
      "en": "Netherite Scrap",
      "zh": "下界合金碎片"
    },
    {
      "id": "diamond",
      "en": "Diamond",
      "zh": "钻石"
    },
    {
      "id": "emerald",
      "en": "Emerald",
      "zh": "绿宝石"
    },
    {
      "id": "lapis_lazuli",
      "en": "Lapis Lazuli",
      "zh": "青金石"
    },
    {
      "id": "redstone",
      "en": "Redstone Dust",
      "zh": "红石粉"
    },
    {
      "id": "amethyst_shard",
      "en": "Amethyst Shard",
      "zh": "紫水晶碎片"
    },
    {
      "id": "quartz",
      "en": "Nether Quartz",
      "zh": "下界石英"
    },
    {
      "id": "gold_nugget",
      "en": "Gold Nugget",
      "zh": "金粒"
    },
    {
      "id": "iron_nugget",
      "en": "Iron Nugget",
      "zh": "铁粒"
    },
    {
      "id": "nether_star",
      "en": "Nether Star",
      "zh": "下界之星"
    },
    {
      "id": "echo_shard",
      "en": "Echo Shard",
      "zh": "回响碎片"
    },
    {
      "id": "netherite_upgrade_smithing_template",
      "en": "Netherite Upgrade",
      "zh": "锻造模板：下界合金升级"
    },
    {
      "id": "stone",
      "en": "Stone",
      "zh": "石头"
    },
    {
      "id": "cobblestone",
      "en": "Cobblestone",
      "zh": "圆石"
    },
    {
      "id": "deepslate",
      "en": "Deepslate",
      "zh": "深板岩"
    },
    {
      "id": "cobbled_deepslate",
      "en": "Cobbled Deepslate",
      "zh": "深板岩圆石"
    },
    {
      "id": "granite",
      "en": "Granite",
      "zh": "花岗岩"
    },
    {
      "id": "andesite",
      "en": "Andesite",
      "zh": "安山岩"
    },
    {
      "id": "diorite",
      "en": "Diorite",
      "zh": "闪长岩"
    },
    {
      "id": "dirt",
      "en": "Dirt",
      "zh": "泥土"
    },
    {
      "id": "grass_block",
      "en": "Grass Block",
      "zh": "草方块"
    },
    {
      "id": "sand",
      "en": "Sand",
      "zh": "沙子"
    },
    {
      "id": "red_sand",
      "en": "Red Sand",
      "zh": "红沙"
    },
    {
      "id": "gravel",
      "en": "Gravel",
      "zh": "沙砾"
    },
    {
      "id": "clay_ball",
      "en": "Clay Ball",
      "zh": "黏土球"
    },
    {
      "id": "sandstone",
      "en": "Sandstone",
      "zh": "砂岩"
    },
    {
      "id": "obsidian",
      "en": "Obsidian",
      "zh": "黑曜石"
    },
    {
      "id": "crying_obsidian",
      "en": "Crying Obsidian",
      "zh": "哭泣的黑曜石"
    },
    {
      "id": "netherrack",
      "en": "Netherrack",
      "zh": "下界岩"
    },
    {
      "id": "end_stone",
      "en": "End Stone",
      "zh": "末地石"
    },
    {
      "id": "prismarine_shard",
      "en": "Prismarine Shard",
      "zh": "海晶碎片"
    },
    {
      "id": "prismarine_crystals",
      "en": "Prismarine Crystals",
      "zh": "海晶砂粒"
    },
    {
      "id": "sea_lantern",
      "en": "Sea Lantern",
      "zh": "海晶灯"
    },
    {
      "id": "glowstone_dust",
      "en": "Glowstone Dust",
      "zh": "荧石粉"
    },
    {
      "id": "glowstone",
      "en": "Glowstone",
      "zh": "荧石"
    },
    {
      "id": "shroomlight",
      "en": "Shroomlight",
      "zh": "菌光体"
    },
    {
      "id": "torch",
      "en": "Torch",
      "zh": "火把"
    },
    {
      "id": "lantern",
      "en": "Lantern",
      "zh": "灯笼"
    },
    {
      "id": "soul_lantern",
      "en": "Soul Lantern",
      "zh": "灵魂灯笼"
    },
    {
      "id": "chain",
      "en": "Chain",
      "zh": "锁链"
    },
    {
      "id": "iron_bars",
      "en": "Iron Bars",
      "zh": "铁栏杆"
    },
    {
      "id": "scaffolding",
      "en": "Scaffolding",
      "zh": "脚手架"
    },
    {
      "id": "glass",
      "en": "Glass",
      "zh": "玻璃"
    },
    {
      "id": "tnt",
      "en": "TNT",
      "zh": "TNT"
    },
    {
      "id": "bookshelf",
      "en": "Bookshelf",
      "zh": "书架"
    },
    {
      "id": "crafting_table",
      "en": "Crafting Table",
      "zh": "工作台"
    },
    {
      "id": "furnace",
      "en": "Furnace",
      "zh": "熔炉"
    },
    {
      "id": "chest",
      "en": "Chest",
      "zh": "箱子"
    },
    {
      "id": "barrel",
      "en": "Barrel",
      "zh": "木桶"
    },
    {
      "id": "ender_chest",
      "en": "Ender Chest",
      "zh": "末影箱"
    },
    {
      "id": "shulker_box",
      "en": "Shulker Box",
      "zh": "潜影盒"
    },
    {
      "id": "white_wool",
      "en": "White Wool",
      "zh": "白色羊毛"
    },
    {
      "id": "black_wool",
      "en": "Black Wool",
      "zh": "黑色羊毛"
    },
    {
      "id": "blue_wool",
      "en": "Blue Wool",
      "zh": "蓝色羊毛"
    },
    {
      "id": "red_wool",
      "en": "Red Wool",
      "zh": "红色羊毛"
    },
    {
      "id": "yellow_wool",
      "en": "Yellow Wool",
      "zh": "黄色羊毛"
    },
    {
      "id": "lime_wool",
      "en": "Lime Wool",
      "zh": "黄绿色羊毛"
    },
    {
      "id": "oak_log",
      "en": "Oak Log",
      "zh": "橡木原木"
    },
    {
      "id": "spruce_log",
      "en": "Spruce Log",
      "zh": "云杉原木"
    },
    {
      "id": "birch_log",
      "en": "Birch Log",
      "zh": "白桦原木"
    },
    {
      "id": "jungle_log",
      "en": "Jungle Log",
      "zh": "丛林原木"
    },
    {
      "id": "acacia_log",
      "en": "Acacia Log",
      "zh": "金合欢原木"
    },
    {
      "id": "dark_oak_log",
      "en": "Dark Oak Log",
      "zh": "深色橡木原木"
    },
    {
      "id": "mangrove_log",
      "en": "Mangrove Log",
      "zh": "红树原木"
    },
    {
      "id": "cherry_log",
      "en": "Cherry Log",
      "zh": "樱花原木"
    },
    {
      "id": "bamboo_block",
      "en": "Bamboo Block",
      "zh": "竹块"
    },
    {
      "id": "crimson_stem",
      "en": "Crimson Stem",
      "zh": "绯红菌柄"
    },
    {
      "id": "warped_stem",
      "en": "Warped Stem",
      "zh": "诡异菌柄"
    },
    {
      "id": "oak_planks",
      "en": "Oak Planks",
      "zh": "橡木木板"
    },
    {
      "id": "stick",
      "en": "Stick",
      "zh": "木棍"
    },
    {
      "id": "bread",
      "en": "Bread",
      "zh": "面包"
    },
    {
      "id": "apple",
      "en": "Apple",
      "zh": "苹果"
    },
    {
      "id": "golden_apple",
      "en": "Golden Apple",
      "zh": "金苹果"
    },
    {
      "id": "enchanted_golden_apple",
      "en": "Enchanted Golden Apple",
      "zh": "附魔金苹果"
    },
    {
      "id": "golden_carrot",
      "en": "Golden Carrot",
      "zh": "金胡萝卜"
    },
    {
      "id": "carrot",
      "en": "Carrot",
      "zh": "胡萝卜"
    },
    {
      "id": "potato",
      "en": "Potato",
      "zh": "马铃薯"
    },
    {
      "id": "baked_potato",
      "en": "Baked Potato",
      "zh": "烤马铃薯"
    },
    {
      "id": "beetroot",
      "en": "Beetroot",
      "zh": "甜菜根"
    },
    {
      "id": "sweet_berries",
      "en": "Sweet Berries",
      "zh": "甜浆果"
    },
    {
      "id": "glow_berries",
      "en": "Glow Berries",
      "zh": "发光浆果"
    },
    {
      "id": "pumpkin_pie",
      "en": "Pumpkin Pie",
      "zh": "南瓜派"
    },
    {
      "id": "cookie",
      "en": "Cookie",
      "zh": "曲奇"
    },
    {
      "id": "honey_bottle",
      "en": "Honey Bottle",
      "zh": "蜂蜜瓶"
    },
    {
      "id": "cooked_beef",
      "en": "Cooked Beef",
      "zh": "熟牛排"
    },
    {
      "id": "cooked_porkchop",
      "en": "Cooked Porkchop",
      "zh": "熟猪排"
    },
    {
      "id": "cooked_chicken",
      "en": "Cooked Chicken",
      "zh": "熟鸡肉"
    },
    {
      "id": "cooked_cod",
      "en": "Cooked Cod",
      "zh": "熟鳕鱼"
    },
    {
      "id": "cooked_salmon",
      "en": "Cooked Salmon",
      "zh": "熟鲑鱼"
    },
    {
      "id": "dried_kelp",
      "en": "Dried Kelp",
      "zh": "干海带"
    },
    {
      "id": "potion",
      "en": "Potion",
      "zh": "药水"
    },
    {
      "id": "splash_potion",
      "en": "Splash Potion",
      "zh": "喷溅药水"
    },
    {
      "id": "lingering_potion",
      "en": "Lingering Potion",
      "zh": "滞留药水"
    },
    {
      "id": "experience_bottle",
      "en": "Bottle o' Enchanting",
      "zh": "附魔之瓶"
    },
    {
      "id": "fire_charge",
      "en": "Fire Charge",
      "zh": "火焰弹"
    },
    {
      "id": "ender_pearl",
      "en": "Ender Pearl",
      "zh": "末影珍珠"
    },
    {
      "id": "ender_eye",
      "en": "Eye of Ender",
      "zh": "末影之眼"
    },
    {
      "id": "snowball",
      "en": "Snowball",
      "zh": "雪球"
    },
    {
      "id": "egg",
      "en": "Egg",
      "zh": "鸡蛋"
    },
    {
      "id": "book",
      "en": "Book",
      "zh": "书"
    },
    {
      "id": "enchanted_book",
      "en": "Enchanted Book",
      "zh": "附魔书"
    },
    {
      "id": "paper",
      "en": "Paper",
      "zh": "纸"
    },
    {
      "id": "bone",
      "en": "Bone",
      "zh": "骨头"
    },
    {
      "id": "blaze_rod",
      "en": "Blaze Rod",
      "zh": "烈焰棒"
    },
    {
      "id": "blaze_powder",
      "en": "Blaze Powder",
      "zh": "烈焰粉"
    },
    {
      "id": "ghast_tear",
      "en": "Ghast Tear",
      "zh": "恶魂之泪"
    },
    {
      "id": "magma_cream",
      "en": "Magma Cream",
      "zh": "岩浆膏"
    },
    {
      "id": "phantom_membrane",
      "en": "Phantom Membrane",
      "zh": "幻翼膜"
    },
    {
      "id": "slime_ball",
      "en": "Slimeball",
      "zh": "黏液球"
    },
    {
      "id": "totem_of_undying",
      "en": "Totem of Undying",
      "zh": "不死图腾"
    },
    {
      "id": "shulker_shell",
      "en": "Shulker Shell",
      "zh": "潜影壳"
    },
    {
      "id": "heart_of_the_sea",
      "en": "Heart of the Sea",
      "zh": "海洋之心"
    },
    {
      "id": "nautilus_shell",
      "en": "Nautilus Shell",
      "zh": "鹦鹉螺壳"
    },
    {
      "id": "wind_charge",
      "en": "Wind Charge",
      "zh": "风弹"
    },
    {
      "id": "goat_horn",
      "en": "Goat Horn",
      "zh": "山羊角"
    },
    {
      "id": "disc_fragment_5",
      "en": "Disc Fragment (5)",
      "zh": "唱片残片（5）"
    },
    {
      "id": "music_disc_cat",
      "en": "Music Disc — Cat",
      "zh": "音乐唱片 — Cat"
    },
    {
      "id": "music_disc_pigstep",
      "en": "Music Disc — Pigstep",
      "zh": "音乐唱片 — Pigstep"
    },
    {
      "id": "music_disc_otherside",
      "en": "Music Disc — Otherside",
      "zh": "音乐唱片 — Otherside"
    },
    {
      "id": "leather",
      "en": "Leather",
      "zh": "皮革"
    },
    {
      "id": "rabbit_hide",
      "en": "Rabbit Hide",
      "zh": "兔子皮"
    },
    {
      "id": "ink_sac",
      "en": "Ink Sac",
      "zh": "墨囊"
    },
    {
      "id": "glow_ink_sac",
      "en": "Glow Ink Sac",
      "zh": "发光墨囊"
    },
    {
      "id": "honeycomb",
      "en": "Honeycomb",
      "zh": "蜜脾"
    },
    {
      "id": "scute",
      "en": "Scute",
      "zh": "鳞甲"
    },
    {
      "id": "spider_eye",
      "en": "Spider Eye",
      "zh": "蜘蛛眼"
    },
    {
      "id": "gunpowder",
      "en": "Gunpowder",
      "zh": "火药"
    },
    {
      "id": "bone_meal",
      "en": "Bone Meal",
      "zh": "骨粉"
    },
    {
      "id": "sugar",
      "en": "Sugar",
      "zh": "糖"
    },
    {
      "id": "breeze_rod",
      "en": "Breeze Rod",
      "zh": "旋风棒"
    },
    {
      "id": "heavy_core",
      "en": "Heavy Core",
      "zh": "重型核心"
    },
    {
      "id": "modern_kinetic_gun",
      "en": "TACZ Gun",
      "zh": "TACZ 枪械",
      "tacz": true
    },
    {
      "id": "ammo",
      "en": "TACZ Ammo",
      "zh": "TACZ 弹药",
      "tacz": true
    }
  ],
  "examples": [
    {
      "key": "weapon_dealer",
      "file": "weapon_dealer.json",
      "desc": {
        "en": "Weapon vendor terminal",
        "zh": "武器供应商终端"
      },
      "box": {
        "name": "#FF5555 武器供应商终端",
        "type": "terminal",
        "drop": 0.05,
        "random": [
          10,
          20,
          40,
          80,
          160
        ],
        "grade5": [
          {
            "id": "minecraft:netherite_sword"
          },
          {
            "id": "minecraft:trident"
          },
          {
            "id": "minecraft:bow",
            "components": {
              "minecraft:enchantments": {
                "minecraft:power": 5
              }
            }
          }
        ],
        "grade4": [
          {
            "id": "minecraft:diamond_sword"
          },
          {
            "id": "minecraft:crossbow",
            "components": {
              "minecraft:enchantments": {
                "minecraft:multishot": 1
              }
            }
          }
        ],
        "grade3": [
          {
            "id": "minecraft:golden_sword"
          },
          {
            "id": "minecraft:shield"
          }
        ],
        "grade2": [
          {
            "id": "minecraft:iron_sword"
          },
          {
            "id": "minecraft:bow"
          },
          {
            "id": "minecraft:arrow",
            "count": 64
          }
        ],
        "grade1": [
          {
            "id": "minecraft:wooden_sword"
          },
          {
            "id": "minecraft:stone_axe"
          },
          {
            "id": "minecraft:leather_helmet"
          }
        ]
      },
      "prices": {
        "minecraft:arrow": 200,
        "minecraft:bow": 200,
        "minecraft:cooked_beef": 50,
        "minecraft:crossbow": 1500,
        "minecraft:diamond": 200,
        "minecraft:diamond_block": 1500,
        "minecraft:diamond_sword": 1500,
        "minecraft:elytra": 4000,
        "minecraft:emerald_block": 500,
        "minecraft:enchanted_book": 500,
        "minecraft:ender_chest": 200,
        "minecraft:ender_pearl": 500,
        "minecraft:experience_bottle": 200,
        "minecraft:gold_ingot": 50,
        "minecraft:golden_apple": 500,
        "minecraft:golden_sword": 500,
        "minecraft:iron_ingot": 50,
        "minecraft:iron_sword": 200,
        "minecraft:leather_helmet": 50,
        "minecraft:nether_star": 1500,
        "minecraft:netherite_sword": 4000,
        "minecraft:shield": 500,
        "minecraft:shulker_box": 4000,
        "minecraft:stone_axe": 50,
        "minecraft:totem_of_undying": 1500,
        "minecraft:trident": 4000,
        "minecraft:wooden_sword": 50,
        "minecraft:nautilus_shell": [
          200,
          400
        ]
      }
    },
    {
      "key": "enchant_vendor",
      "file": "enchant_vendor.json",
      "desc": {
        "en": "Enchanted book vendor terminal",
        "zh": "附魔书终端"
      },
      "box": {
        "name": "#00E5FF 附魔书终端",
        "type": "terminal",
        "drop": 0.04,
        "random": [
          15,
          30,
          60,
          120,
          220
        ],
        "grade5": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:mending": 1
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:sharpness": 5
              }
            }
          }
        ],
        "grade4": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:protection": 4
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:efficiency": 5
              }
            }
          }
        ],
        "grade3": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:fire_aspect": 2
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:looting": 3
              }
            }
          }
        ],
        "grade2": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:unbreaking": 3
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:silk_touch": 1
              }
            }
          }
        ],
        "grade1": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:fortune": 1
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:smite": 2
              }
            }
          }
        ],
        "entity": [
          "minecraft:witch"
        ]
      },
      "prices": {
        "minecraft:arrow": 200,
        "minecraft:bow": 200,
        "minecraft:cooked_beef": 50,
        "minecraft:crossbow": 1500,
        "minecraft:diamond": 200,
        "minecraft:diamond_block": 1500,
        "minecraft:diamond_sword": 1500,
        "minecraft:elytra": 4000,
        "minecraft:emerald_block": 500,
        "minecraft:enchanted_book": 500,
        "minecraft:ender_chest": 200,
        "minecraft:ender_pearl": 500,
        "minecraft:experience_bottle": 200,
        "minecraft:gold_ingot": 50,
        "minecraft:golden_apple": 500,
        "minecraft:golden_sword": 500,
        "minecraft:iron_ingot": 50,
        "minecraft:iron_sword": 200,
        "minecraft:leather_helmet": 50,
        "minecraft:nether_star": 1500,
        "minecraft:netherite_sword": 4000,
        "minecraft:shield": 500,
        "minecraft:shulker_box": 4000,
        "minecraft:stone_axe": 50,
        "minecraft:totem_of_undying": 1500,
        "minecraft:trident": 4000,
        "minecraft:wooden_sword": 50,
        "minecraft:nautilus_shell": [
          200,
          400
        ]
      }
    },
    {
      "key": "supply_outpost",
      "file": "supply_outpost.json",
      "desc": {
        "en": "Survival supply terminal",
        "zh": "生存补给终端"
      },
      "box": {
        "name": "#FFAA00 生存补给终端",
        "type": "terminal",
        "drop": 0.03,
        "random": [
          25,
          50,
          100,
          200,
          400
        ],
        "grade5": [
          {
            "id": "minecraft:shulker_box",
            "count": 1
          },
          {
            "id": "minecraft:elytra"
          }
        ],
        "grade4": [
          {
            "id": "minecraft:nether_star"
          },
          {
            "id": "minecraft:diamond_block"
          },
          {
            "id": "minecraft:totem_of_undying"
          }
        ],
        "grade3": [
          {
            "id": "minecraft:golden_apple"
          },
          {
            "id": "minecraft:ender_pearl",
            "count": 16
          },
          {
            "id": "minecraft:emerald_block"
          }
        ],
        "grade2": [
          {
            "id": "minecraft:diamond",
            "count": 16
          },
          {
            "id": "minecraft:ender_chest"
          },
          {
            "id": "minecraft:experience_bottle",
            "count": 32
          }
        ],
        "grade1": [
          {
            "id": "minecraft:iron_ingot",
            "count": 32
          },
          {
            "id": "minecraft:cooked_beef",
            "count": 64
          },
          {
            "id": "minecraft:gold_ingot",
            "count": 16
          }
        ],
        "entity": [
          "minecraft:zombie",
          0.1,
          "minecraft:skeleton",
          0.08,
          "minecraft:creeper",
          0.05
        ]
      },
      "prices": {
        "minecraft:arrow": 200,
        "minecraft:bow": 200,
        "minecraft:cooked_beef": 50,
        "minecraft:crossbow": 1500,
        "minecraft:diamond": 200,
        "minecraft:diamond_block": 1500,
        "minecraft:diamond_sword": 1500,
        "minecraft:elytra": 4000,
        "minecraft:emerald_block": 500,
        "minecraft:enchanted_book": 500,
        "minecraft:ender_chest": 200,
        "minecraft:ender_pearl": 500,
        "minecraft:experience_bottle": 200,
        "minecraft:gold_ingot": 50,
        "minecraft:golden_apple": 500,
        "minecraft:golden_sword": 500,
        "minecraft:iron_ingot": 50,
        "minecraft:iron_sword": 200,
        "minecraft:leather_helmet": 50,
        "minecraft:nether_star": 1500,
        "minecraft:netherite_sword": 4000,
        "minecraft:shield": 500,
        "minecraft:shulker_box": 4000,
        "minecraft:stone_axe": 50,
        "minecraft:totem_of_undying": 1500,
        "minecraft:trident": 4000,
        "minecraft:wooden_sword": 50,
        "minecraft:nautilus_shell": [
          200,
          400
        ]
      }
    },
    {
      "key": "tacz_gun_crate",
      "file": "gun_crate.json",
      "desc": {
        "en": "TACZ gun crate (compat pack)",
        "zh": "TACZ 军火枪械箱（联动包）"
      },
      "box": {
        "name": "#AA3333 军火枪械箱",
        "key": "csgobox:csgo_key3",
        "drop": 0.02,
        "random": [
          625,
          125,
          25,
          6,
          4
        ],
        "requires": [
          "tacz"
        ],
        "grade5": [
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:ak47\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:m4a1\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:ai_awp\"}"
          },
          {
            "id": "minecraft:netherite_ingot",
            "count": 2
          }
        ],
        "grade4": [
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:kar98\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:rpk\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:sks_tactical\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 64,
            "tag": "{AmmoId:\"tacz:762x39\"}"
          }
        ],
        "grade3": [
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:m1911\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:glock_17\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 32,
            "tag": "{AmmoId:\"tacz:9mm\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 32,
            "tag": "{AmmoId:\"tacz:45acp\"}"
          }
        ],
        "grade2": [
          {
            "id": "tacz:ammo",
            "count": 16,
            "tag": "{AmmoId:\"tacz:9mm\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 16,
            "tag": "{AmmoId:\"tacz:45acp\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 16,
            "tag": "{AmmoId:\"tacz:762x39\"}"
          },
          {
            "id": "minecraft:gunpowder",
            "count": 8
          }
        ],
        "grade1": [
          {
            "id": "minecraft:gunpowder",
            "count": 4
          },
          {
            "id": "minecraft:iron_nugget",
            "count": 16
          },
          {
            "id": "minecraft:iron_ingot",
            "count": 6
          }
        ]
      },
      "prices": {
        "minecraft:gunpowder": 100,
        "tacz:ammo#tacz:12g": 1500,
        "tacz:ammo#tacz:45acp": 150,
        "tacz:ammo#tacz:556x45": 400,
        "tacz:ammo#tacz:762x39": 400,
        "tacz:ammo#tacz:9mm": 150,
        "tacz:modern_kinetic_gun#tacz:ai_awp": 22000,
        "tacz:modern_kinetic_gun#tacz:ak47": 2000,
        "tacz:modern_kinetic_gun#tacz:cz75": 450,
        "tacz:modern_kinetic_gun#tacz:deagle": 4500,
        "tacz:modern_kinetic_gun#tacz:deagle_golden": 30000,
        "tacz:modern_kinetic_gun#tacz:g36k": 1800,
        "tacz:modern_kinetic_gun#tacz:glock_17": 500,
        "tacz:modern_kinetic_gun#tacz:hk416d": 2500,
        "tacz:modern_kinetic_gun#tacz:kar98": 3500,
        "tacz:modern_kinetic_gun#tacz:m1014": 9000,
        "tacz:modern_kinetic_gun#tacz:m107": 26000,
        "tacz:modern_kinetic_gun#tacz:m16a4": 1800,
        "tacz:modern_kinetic_gun#tacz:m1911": 500,
        "tacz:modern_kinetic_gun#tacz:m249": 11000,
        "tacz:modern_kinetic_gun#tacz:m4a1": 2000,
        "tacz:modern_kinetic_gun#tacz:m700": 3500,
        "tacz:modern_kinetic_gun#tacz:minigun": 12000,
        "tacz:modern_kinetic_gun#tacz:mk14": 4500,
        "tacz:modern_kinetic_gun#tacz:p320": 450,
        "tacz:modern_kinetic_gun#tacz:rpg7": 14000,
        "tacz:modern_kinetic_gun#tacz:rpk": 10000,
        "tacz:modern_kinetic_gun#tacz:sks_tactical": 3500,
        "tacz:modern_kinetic_gun#tacz:spas_12": 3000,
        "tacz:modern_kinetic_gun#tacz:timeless50": 30000,
        "tacz:modern_kinetic_gun#tacz:ump45": 1500
      }
    }
  ]
};
