// AUTO-GENERATED by scripts/sync-box-editor-data.py - do not edit by hand.
// Run `python scripts/sync-box-editor-data.py` after changing
// docs/box-schema/*.schema.json or the bundled examples.
window.CSBDATA = {
  "schemas": {
    "box": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://csgobox.reclizer.com/schemas/box.schema.json",
      "title": "CS2-Box Box Definition",
      "description": "Schema for a CS2-Box crate / terminal definition (config/csbox/<id>.json). The file name (minus .json) becomes the box id. Terminal prices are NOT part of box files anymore — they live in the central price table config/csbox/_prices.json (see prices.schema.json); a leftover 'price' field is rejected by the runtime validator. Runtime validation in-game is authoritative; this schema is an authoring aid for IDE autocomplete / offline checks.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Display name shown on the box item and GUI. May start with a '#RRGGBB ' color prefix (e.g. \"#FF5555 神化宝石箱\")."
        },
        "type": {
          "type": "string",
          "enum": [
            "csbox",
            "terminal"
          ],
          "description": "csbox = regular crate (default), terminal = terminal machine. Terminals must NOT declare a key field."
        },
        "key": {
          "type": "string",
          "description": "Key item id required to open. Use minecraft:air for a keyless box. Terminals forbid this field."
        },
        "drop": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0,
          "description": "Default entity drop chance (0.0-1.0)."
        },
        "random": {
          "type": "array",
          "minItems": 5,
          "maxItems": 5,
          "items": {
            "type": "integer",
            "minimum": 0,
            "maximum": 10000
          },
          "description": "Five grade weights ordered grade1(common)..grade5(rare). Non-positive uses defaults; >10000 clamps."
        },
        "entity": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0
              }
            ]
          },
          "description": "Entity ids that drop this box, or alternating id/rate pairs."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "v2.1.0: false skips this box entirely (no error)."
        },
        "requires": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "v2.1.0: list of mod ids that must be loaded; the box is skipped with an error when any is missing."
        },
        "icon": {
          "oneOf": [
            {
              "type": "string",
              "description": "Item-model id (26.x renders directly; other versions warn)"
            },
            {
              "type": "integer",
              "minimum": 0,
              "description": "CustomModelData value (pair with a resource pack)"
            }
          ],
          "description": "v2.1.0: per-box icon override."
        },
        "discount": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0,
          "default": 0.0,
          "description": "v2.1.0: terminal price discount (0..1 off), e.g. 0.2 = 20% off."
        },
        "stock": {
          "type": "integer",
          "minimum": -1,
          "default": -1,
          "description": "v2.1.0: terminal stock limit; -1 = unlimited."
        },
        "restock_minutes": {
          "type": "integer",
          "minimum": 0,
          "default": 0,
          "description": "v2.1.0: minutes between stock refills; 0 = never auto-restock."
        },
        "max_per_player": {
          "type": "integer",
          "minimum": -1,
          "default": -1,
          "description": "v2.1.0: per-player open cap; -1 = unlimited (in-memory, resets on restart)."
        },
        "cooldown_seconds": {
          "type": "integer",
          "minimum": 0,
          "default": 0,
          "description": "v2.1.0: per-box open cooldown; 0 = none."
        },
        "permission": {
          "type": "string",
          "description": "v2.1.0: permission node checked against the PERMISSION_GATE hook (default allow-all)."
        },
        "grade1": {
          "$ref": "#/$defs/grade"
        },
        "grade2": {
          "$ref": "#/$defs/grade"
        },
        "grade3": {
          "$ref": "#/$defs/grade"
        },
        "grade4": {
          "$ref": "#/$defs/grade"
        },
        "grade5": {
          "$ref": "#/$defs/grade"
        }
      },
      "$defs": {
        "grade": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/item"
          },
          "description": "Items in this grade tier (grade1 lowest rarity .. grade5 highest)."
        },
        "item": {
          "type": "object",
          "description": "One item pool entry. Exactly one source: id, '#tag' or loot_table. Terminal prices come from the central _prices.json table, never from this object.",
          "properties": {
            "id": {
              "type": "string",
              "description": "Item registry id, e.g. minecraft:diamond_sword."
            },
            "tag": {
              "type": "string",
              "description": "Item tag reference starting with '#', e.g. #minecraft:swords. Expanded at load time."
            },
            "loot_table": {
              "type": "string",
              "description": "Loot table reference, e.g. minecraft:chests/simple_dungeon. Rolled at open time."
            },
            "count": {
              "oneOf": [
                {
                  "type": "integer",
                  "minimum": 1
                },
                {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": {
                    "type": "integer",
                    "minimum": 1
                  }
                }
              ],
              "description": "Item count, or [min,max] rolled at open time (v2.1.0)."
            },
            "weight": {
              "type": "integer",
              "minimum": 0,
              "default": 1,
              "description": "v2.1.0: intra-grade weight; 0 disables the entry."
            },
            "enchant": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Enchantment id, e.g. minecraft:sharpness"
                    },
                    "level": {
                      "oneOf": [
                        {
                          "type": "integer",
                          "minimum": 1
                        },
                        {
                          "type": "array",
                          "minItems": 2,
                          "maxItems": 2,
                          "items": {
                            "type": "integer",
                            "minimum": 1
                          }
                        }
                      ],
                      "description": "Fixed level or [min,max] range."
                    }
                  },
                  "additionalProperties": false
                }
              ],
              "description": "v2.1.0: random-enchant shortcut (true = any enchant, or {id, level})."
            },
            "price": {
              "not": {},
              "description": "REMOVED — do not use. Terminal prices are centrally managed in config/csbox/_prices.json (see prices.schema.json). A leftover price here is reported by the in-game validator; this item then falls back to the grade default price until migrated."
            },
            "components": {
              "type": "object",
              "description": "Data components (1.21+/26.x). Ignored on 1.20.1."
            },
            "tag_nbt": {
              "type": "string",
              "description": "Legacy NBT tag string (1.20.1 / old configs)."
            }
          },
          "oneOf": [
            {
              "required": [
                "id"
              ]
            },
            {
              "required": [
                "tag"
              ]
            },
            {
              "required": [
                "loot_table"
              ]
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "prices": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://csgobox.reclizer.com/schemas/prices.schema.json",
      "title": "CS2-Box Price Table",
      "description": "Central terminal price table (config/csbox/_prices.json). Keys are item registry ids ('minecraft:diamond_sword') or id#variant sub-keys for NBT-distinguished items ('tacz:modern_kinetic_gun#tacz:deagle_golden'); values are non-negative integers in Armory Points. Items without an entry use the grade default price (grade1..5 = 6/10/16/22/30). The underscore prefix keeps the file out of the box scan.",
      "type": "object",
      "propertyNames": {
        "pattern": "^[a-z0-9_.-]+:[a-z0-9_./-]+(#.+)?$"
      },
      "additionalProperties": {
        "type": "integer",
        "minimum": 0,
        "description": "Terminal purchase price in Armory Points for the item id (or id#variant)."
      }
    }
  },
  "versions": [
    {
      "key": "1.21.1",
      "label": {
        "en": "1.21.1 (NeoForge)",
        "zh": "1.21.1 (NeoForge)"
      },
      "short": {
        "en": "1.21.1",
        "zh": "1.21.1"
      },
      "taczVariants": true,
      "components": true,
      "note": {
        "en": "Data Components; TACZ GunId/AmmoId variants supported.",
        "zh": "Data Components；支持 TACZ GunId/AmmoId 变体键。"
      }
    },
    {
      "key": "26.1.2",
      "label": {
        "en": "26.1.2",
        "zh": "26.1.2"
      },
      "short": {
        "en": "26.1.2",
        "zh": "26.1.2"
      },
      "taczVariants": false,
      "components": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "26.2",
      "label": {
        "en": "26.2",
        "zh": "26.2"
      },
      "short": {
        "en": "26.2",
        "zh": "26.2"
      },
      "taczVariants": false,
      "components": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "forge-26.1.2",
      "label": {
        "en": "Forge 26.1.2",
        "zh": "Forge 26.1.2"
      },
      "short": {
        "en": "Forge 26.1.2",
        "zh": "Forge 26.1.2"
      },
      "taczVariants": false,
      "components": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "forge-26.2",
      "label": {
        "en": "Forge 26.2",
        "zh": "Forge 26.2"
      },
      "short": {
        "en": "Forge 26.2",
        "zh": "Forge 26.2"
      },
      "taczVariants": false,
      "components": true,
      "note": {
        "en": "Data Components; no id#variant price keys.",
        "zh": "Data Components；价格表不使用 id#变体 子键。"
      }
    },
    {
      "key": "forge-1.20.1",
      "label": {
        "en": "Forge 1.20.1",
        "zh": "Forge 1.20.1"
      },
      "short": {
        "en": "Forge 1.20.1",
        "zh": "Forge 1.20.1"
      },
      "taczVariants": true,
      "components": false,
      "note": {
        "en": "Legacy NBT tag (no Data Components); TACZ variants supported.",
        "zh": "旧版 NBT tag（无 Data Components）；支持 TACZ 变体键。"
      }
    }
  ],
  "gradeNames": [
    {
      "id": "consumer",
      "zh": "消费级（灰）",
      "en": "Consumer (Gray)"
    },
    {
      "id": "industrial",
      "zh": "工业级（浅蓝）",
      "en": "Industrial (Light Blue)"
    },
    {
      "id": "mil_spec",
      "zh": "军规级（蓝）",
      "en": "Mil-Spec (Blue)"
    },
    {
      "id": "restricted",
      "zh": "受限级（紫）",
      "en": "Restricted (Purple)"
    },
    {
      "id": "classified",
      "zh": "保密级（粉/红）",
      "en": "Classified (Pink/Red)"
    }
  ],
  "gradeDefaultPrices": [
    6,
    10,
    16,
    22,
    30
  ],
  "gradeRecycleYields": [
    3,
    5,
    7,
    8,
    8
  ],
  "examples": [
    {
      "key": "weapon_dealer",
      "file": "weapon_dealer.json",
      "desc": {
        "en": "Weapon vendor terminal",
        "zh": "武器供应商终端"
      },
      "box": {
        "name": "#FF5555 武器供应商终端",
        "type": "terminal",
        "drop": 0.05,
        "random": [
          10,
          20,
          40,
          80,
          160
        ],
        "grade5": [
          {
            "id": "minecraft:netherite_sword"
          },
          {
            "id": "minecraft:trident"
          },
          {
            "id": "minecraft:bow",
            "components": {
              "minecraft:enchantments": {
                "minecraft:power": 5
              }
            }
          }
        ],
        "grade4": [
          {
            "id": "minecraft:diamond_sword"
          },
          {
            "id": "minecraft:crossbow",
            "components": {
              "minecraft:enchantments": {
                "minecraft:multishot": 1
              }
            }
          }
        ],
        "grade3": [
          {
            "id": "minecraft:golden_sword"
          },
          {
            "id": "minecraft:shield"
          }
        ],
        "grade2": [
          {
            "id": "minecraft:iron_sword"
          },
          {
            "id": "minecraft:bow"
          },
          {
            "id": "minecraft:arrow",
            "count": 64
          }
        ],
        "grade1": [
          {
            "id": "minecraft:wooden_sword"
          },
          {
            "id": "minecraft:stone_axe"
          },
          {
            "id": "minecraft:leather_helmet"
          }
        ]
      },
      "prices": {
        "minecraft:arrow": 200,
        "minecraft:bow": 200,
        "minecraft:cooked_beef": 50,
        "minecraft:crossbow": 1500,
        "minecraft:diamond": 200,
        "minecraft:diamond_block": 1500,
        "minecraft:diamond_sword": 1500,
        "minecraft:elytra": 4000,
        "minecraft:emerald_block": 500,
        "minecraft:enchanted_book": 500,
        "minecraft:ender_chest": 200,
        "minecraft:ender_pearl": 500,
        "minecraft:experience_bottle": 200,
        "minecraft:gold_ingot": 50,
        "minecraft:golden_apple": 500,
        "minecraft:golden_sword": 500,
        "minecraft:iron_ingot": 50,
        "minecraft:iron_sword": 200,
        "minecraft:leather_helmet": 50,
        "minecraft:nether_star": 1500,
        "minecraft:netherite_sword": 4000,
        "minecraft:shield": 500,
        "minecraft:shulker_box": 4000,
        "minecraft:stone_axe": 50,
        "minecraft:totem_of_undying": 1500,
        "minecraft:trident": 4000,
        "minecraft:wooden_sword": 50
      }
    },
    {
      "key": "enchant_vendor",
      "file": "enchant_vendor.json",
      "desc": {
        "en": "Enchanted book vendor terminal",
        "zh": "附魔书终端"
      },
      "box": {
        "name": "#00E5FF 附魔书终端",
        "type": "terminal",
        "drop": 0.04,
        "random": [
          15,
          30,
          60,
          120,
          220
        ],
        "grade5": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:mending": 1
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:sharpness": 5
              }
            }
          }
        ],
        "grade4": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:protection": 4
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:efficiency": 5
              }
            }
          }
        ],
        "grade3": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:fire_aspect": 2
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:looting": 3
              }
            }
          }
        ],
        "grade2": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:unbreaking": 3
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:silk_touch": 1
              }
            }
          }
        ],
        "grade1": [
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:fortune": 1
              }
            }
          },
          {
            "id": "minecraft:enchanted_book",
            "components": {
              "minecraft:stored_enchantments": {
                "minecraft:smite": 2
              }
            }
          }
        ],
        "entity": [
          "minecraft:witch"
        ]
      },
      "prices": {
        "minecraft:arrow": 200,
        "minecraft:bow": 200,
        "minecraft:cooked_beef": 50,
        "minecraft:crossbow": 1500,
        "minecraft:diamond": 200,
        "minecraft:diamond_block": 1500,
        "minecraft:diamond_sword": 1500,
        "minecraft:elytra": 4000,
        "minecraft:emerald_block": 500,
        "minecraft:enchanted_book": 500,
        "minecraft:ender_chest": 200,
        "minecraft:ender_pearl": 500,
        "minecraft:experience_bottle": 200,
        "minecraft:gold_ingot": 50,
        "minecraft:golden_apple": 500,
        "minecraft:golden_sword": 500,
        "minecraft:iron_ingot": 50,
        "minecraft:iron_sword": 200,
        "minecraft:leather_helmet": 50,
        "minecraft:nether_star": 1500,
        "minecraft:netherite_sword": 4000,
        "minecraft:shield": 500,
        "minecraft:shulker_box": 4000,
        "minecraft:stone_axe": 50,
        "minecraft:totem_of_undying": 1500,
        "minecraft:trident": 4000,
        "minecraft:wooden_sword": 50
      }
    },
    {
      "key": "supply_outpost",
      "file": "supply_outpost.json",
      "desc": {
        "en": "Survival supply terminal",
        "zh": "生存补给终端"
      },
      "box": {
        "name": "#FFAA00 生存补给终端",
        "type": "terminal",
        "drop": 0.03,
        "random": [
          25,
          50,
          100,
          200,
          400
        ],
        "grade5": [
          {
            "id": "minecraft:shulker_box",
            "count": 1
          },
          {
            "id": "minecraft:elytra"
          }
        ],
        "grade4": [
          {
            "id": "minecraft:nether_star"
          },
          {
            "id": "minecraft:diamond_block"
          },
          {
            "id": "minecraft:totem_of_undying"
          }
        ],
        "grade3": [
          {
            "id": "minecraft:golden_apple"
          },
          {
            "id": "minecraft:ender_pearl",
            "count": 16
          },
          {
            "id": "minecraft:emerald_block"
          }
        ],
        "grade2": [
          {
            "id": "minecraft:diamond",
            "count": 16
          },
          {
            "id": "minecraft:ender_chest"
          },
          {
            "id": "minecraft:experience_bottle",
            "count": 32
          }
        ],
        "grade1": [
          {
            "id": "minecraft:iron_ingot",
            "count": 32
          },
          {
            "id": "minecraft:cooked_beef",
            "count": 64
          },
          {
            "id": "minecraft:gold_ingot",
            "count": 16
          }
        ],
        "entity": [
          "minecraft:zombie",
          0.1,
          "minecraft:skeleton",
          0.08,
          "minecraft:creeper",
          0.05
        ]
      },
      "prices": {
        "minecraft:arrow": 200,
        "minecraft:bow": 200,
        "minecraft:cooked_beef": 50,
        "minecraft:crossbow": 1500,
        "minecraft:diamond": 200,
        "minecraft:diamond_block": 1500,
        "minecraft:diamond_sword": 1500,
        "minecraft:elytra": 4000,
        "minecraft:emerald_block": 500,
        "minecraft:enchanted_book": 500,
        "minecraft:ender_chest": 200,
        "minecraft:ender_pearl": 500,
        "minecraft:experience_bottle": 200,
        "minecraft:gold_ingot": 50,
        "minecraft:golden_apple": 500,
        "minecraft:golden_sword": 500,
        "minecraft:iron_ingot": 50,
        "minecraft:iron_sword": 200,
        "minecraft:leather_helmet": 50,
        "minecraft:nether_star": 1500,
        "minecraft:netherite_sword": 4000,
        "minecraft:shield": 500,
        "minecraft:shulker_box": 4000,
        "minecraft:stone_axe": 50,
        "minecraft:totem_of_undying": 1500,
        "minecraft:trident": 4000,
        "minecraft:wooden_sword": 50
      }
    },
    {
      "key": "tacz_gun_crate",
      "file": "gun_crate.json",
      "desc": {
        "en": "TACZ gun crate (compat pack)",
        "zh": "TACZ 军火枪械箱（联动包）"
      },
      "box": {
        "name": "#AA3333 军火枪械箱",
        "key": "csgobox:csgo_key3",
        "drop": 0.02,
        "random": [
          625,
          125,
          25,
          6,
          4
        ],
        "requires": [
          "tacz"
        ],
        "grade5": [
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:ak47\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:m4a1\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:ai_awp\"}"
          },
          {
            "id": "minecraft:netherite_ingot",
            "count": 2
          }
        ],
        "grade4": [
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:kar98\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:rpk\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:sks_tactical\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 64,
            "tag": "{AmmoId:\"tacz:762x39\"}"
          }
        ],
        "grade3": [
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:m1911\"}"
          },
          {
            "id": "tacz:modern_kinetic_gun",
            "count": 1,
            "tag": "{GunId:\"tacz:glock_17\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 32,
            "tag": "{AmmoId:\"tacz:9mm\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 32,
            "tag": "{AmmoId:\"tacz:45acp\"}"
          }
        ],
        "grade2": [
          {
            "id": "tacz:ammo",
            "count": 16,
            "tag": "{AmmoId:\"tacz:9mm\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 16,
            "tag": "{AmmoId:\"tacz:45acp\"}"
          },
          {
            "id": "tacz:ammo",
            "count": 16,
            "tag": "{AmmoId:\"tacz:762x39\"}"
          },
          {
            "id": "minecraft:gunpowder",
            "count": 8
          }
        ],
        "grade1": [
          {
            "id": "minecraft:gunpowder",
            "count": 4
          },
          {
            "id": "minecraft:iron_nugget",
            "count": 16
          },
          {
            "id": "minecraft:iron_ingot",
            "count": 6
          }
        ]
      },
      "prices": {
        "minecraft:gunpowder": 100,
        "tacz:ammo#tacz:12g": 1500,
        "tacz:ammo#tacz:45acp": 150,
        "tacz:ammo#tacz:556x45": 400,
        "tacz:ammo#tacz:762x39": 400,
        "tacz:ammo#tacz:9mm": 150,
        "tacz:modern_kinetic_gun#tacz:ai_awp": 22000,
        "tacz:modern_kinetic_gun#tacz:ak47": 2000,
        "tacz:modern_kinetic_gun#tacz:cz75": 450,
        "tacz:modern_kinetic_gun#tacz:deagle": 4500,
        "tacz:modern_kinetic_gun#tacz:deagle_golden": 30000,
        "tacz:modern_kinetic_gun#tacz:g36k": 1800,
        "tacz:modern_kinetic_gun#tacz:glock_17": 500,
        "tacz:modern_kinetic_gun#tacz:hk416d": 2500,
        "tacz:modern_kinetic_gun#tacz:kar98": 3500,
        "tacz:modern_kinetic_gun#tacz:m1014": 9000,
        "tacz:modern_kinetic_gun#tacz:m107": 26000,
        "tacz:modern_kinetic_gun#tacz:m16a4": 1800,
        "tacz:modern_kinetic_gun#tacz:m1911": 500,
        "tacz:modern_kinetic_gun#tacz:m249": 11000,
        "tacz:modern_kinetic_gun#tacz:m4a1": 2000,
        "tacz:modern_kinetic_gun#tacz:m700": 3500,
        "tacz:modern_kinetic_gun#tacz:minigun": 12000,
        "tacz:modern_kinetic_gun#tacz:mk14": 4500,
        "tacz:modern_kinetic_gun#tacz:p320": 450,
        "tacz:modern_kinetic_gun#tacz:rpg7": 14000,
        "tacz:modern_kinetic_gun#tacz:rpk": 10000,
        "tacz:modern_kinetic_gun#tacz:sks_tactical": 3500,
        "tacz:modern_kinetic_gun#tacz:spas_12": 3000,
        "tacz:modern_kinetic_gun#tacz:timeless50": 30000,
        "tacz:modern_kinetic_gun#tacz:ump45": 1500
      }
    }
  ]
};
