// Root project: no java compilation. Each subproject applies its own plugins.
plugins {
    id 'base'
}

allprojects {
    group = mod_group_id
    version = mod_version

    repositories {
        maven {
            name = 'LocalPatchedLibraries'
            url = rootProject.file('local-repo')
            metadataSources {
                mavenPom()
                artifact()
            }
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven { url = 'https://libraries.minecraft.net' }
        mavenCentral()
        maven { url = 'https://maven.blamejared.com' }
        maven { url = 'https://modmaven.dev' }
        maven { url = 'https://www.cursemaven.com' }
        maven {
            url = 'https://maven.latvian.dev/releases'
            content {
                includeGroup 'dev.latvian.mods'
                includeGroup 'dev.latvian.apps'
            }
        }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'eclipse'
    apply plugin: 'idea'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(java_toolchain_version as int)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}
