package com.reclizer.csgobox.packet;

import com.reclizer.csgobox.CsgoBox;
import io.netty.handler.codec.DecoderException;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.network.handling.IPayloadContext;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Queue;

/**
 * Server-authoritative box opening result.
 *
 * <p>The request id is generated by the client and echoed by the server only to
 * associate this result with the currently displayed animation. It is not a
 * security token.</p>
 */
public record PacketBoxOpenResult(
        ItemStack item,
        int grade,
        int winningIndex,
        long serverSeed,
        long requestId,
        List<ItemStack> animationItems,
        List<Integer> animationGrades
) implements CustomPacketPayload {

    public static final int ANIMATION_ITEM_COUNT = 50;
    public static final int MIN_WINNING_INDEX = 35;
    public static final int MAX_WINNING_INDEX = 44;
    private static final int MAX_PENDING_RESULTS = 8;

    public static final Type<PacketBoxOpenResult> TYPE = new Type<>(
            ResourceLocation.fromNamespaceAndPath(CsgoBox.MODID, "box_open_result"));

    public static final StreamCodec<RegistryFriendlyByteBuf, PacketBoxOpenResult> STREAM_CODEC = StreamCodec.of(
            PacketBoxOpenResult::write,
            PacketBoxOpenResult::read
    );

    public PacketBoxOpenResult {
        item = item == null ? ItemStack.EMPTY : item.copy();
        grade = Mth.clamp(grade, 1, 5);

        if (animationItems == null) {
            animationItems = List.of();
        }
        if (animationGrades == null) {
            animationGrades = List.of();
        }
        PacketValidation.requireSameSize("animationItems", animationItems, "animationGrades", animationGrades);
        PacketValidation.requireMaxSize("animationItems", animationItems, ANIMATION_ITEM_COUNT);
        animationItems = PacketValidation.copyStacks(animationItems);
        animationGrades = PacketValidation.copyClampedInts(animationGrades, 1, 5, 1);
        winningIndex = animationItems.isEmpty() ? 0 : Mth.clamp(winningIndex, 0, animationItems.size() - 1);
    }

    private static void write(RegistryFriendlyByteBuf buf, PacketBoxOpenResult packet) {
        ItemStack.OPTIONAL_STREAM_CODEC.encode(buf, packet.item);
        buf.writeVarInt(packet.grade);
        buf.writeVarInt(packet.winningIndex);
        buf.writeLong(packet.serverSeed);
        buf.writeLong(packet.requestId);
        buf.writeVarInt(packet.animationItems.size());
        for (int i = 0; i < packet.animationItems.size(); i++) {
            ItemStack.OPTIONAL_STREAM_CODEC.encode(buf, packet.animationItems.get(i));
            buf.writeVarInt(packet.animationGrades.get(i));
        }
    }

    private static PacketBoxOpenResult read(RegistryFriendlyByteBuf buf) {
        ItemStack item = ItemStack.OPTIONAL_STREAM_CODEC.decode(buf);
        int grade = Mth.clamp(buf.readVarInt(), 1, 5);
        int winningIndex = Mth.clamp(buf.readVarInt(), 0, ANIMATION_ITEM_COUNT - 1);
        long serverSeed = buf.readLong();
        long requestId = buf.readLong();
        int animationSize = buf.readVarInt();
        if (animationSize < 0 || animationSize > ANIMATION_ITEM_COUNT) {
            throw new DecoderException("Invalid animation item count: " + animationSize);
        }

        List<ItemStack> animationItems = new ArrayList<>(animationSize);
        List<Integer> animationGrades = new ArrayList<>(animationSize);
        for (int i = 0; i < animationSize; i++) {
            animationItems.add(ItemStack.OPTIONAL_STREAM_CODEC.decode(buf));
            animationGrades.add(Mth.clamp(buf.readVarInt(), 1, 5));
        }
        return new PacketBoxOpenResult(item, grade, winningIndex, serverSeed, requestId, animationItems, animationGrades);
    }

    @Override
    public Type<? extends CustomPacketPayload> type() {
        return TYPE;
    }

    private static final Queue<PacketBoxOpenResult> sPendingResults = new ArrayDeque<>();

    public static void handle(final PacketBoxOpenResult message, final IPayloadContext context) {
        context.enqueueWork(() -> {
            PacketValidation.trimQueue(sPendingResults, MAX_PENDING_RESULTS);
            sPendingResults.add(message);
        });
    }

    public static PacketBoxOpenResult consumeMatching(long requestId) {
        Iterator<PacketBoxOpenResult> iterator = sPendingResults.iterator();
        while (iterator.hasNext()) {
            PacketBoxOpenResult result = iterator.next();
            if (result.requestId() == requestId) {
                iterator.remove();
                return result;
            }
        }
        return null;
    }
}
