modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayURL="https://gitee.com/hou-xiangling/CS2-Box/tree/main/docs/tutorials"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[29.22,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="roughlyenoughitems"
type="optional"
versionRange="[26.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="optional"
versionRange="[26.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
  modId="jade"
  type="optional"
  versionRange="[26.1,)"
  ordering="NONE"
  side="CLIENT"

[[dependencies.${mod_id}]]
  modId="wthit"
  type="optional"
  versionRange="[19.0,)"
  ordering="NONE"
  side="CLIENT"

[[dependencies.${mod_id}]]
  modId="theoneprobe"
  type="optional"
  versionRange="[14.0,)"
  ordering="NONE"
  side="CLIENT"
