package com.reclizer.csgobox.box;

import java.util.Collection;
import java.util.TreeSet;

/**
 * Action-bar "quote cap" tiers (报价上限) derived from the central price table
 * instead of being hard-coded.
 *
 * <p>v2.0.1+: the terminal negotiation screen's cap selector used to offer a
 * fixed {@code {30, 64, 200, 400, 800, unlimited}} list that had no relation
 * to the server's actual economy. The tiers are now generated by scanning
 * {@code config/csbox/_prices.json}: {@value #TIER_COUNT} priced tiers on a
 * geometric (logarithmic) ladder whose top tier is the most expensive entry
 * in the table, followed by the "unlimited" sentinel. A table with no
 * positive price at all (empty, or every entry priced 0) degrades to
 * "unlimited" only.</p>
 *
 * <p>Geometric spacing matters because real tables span several orders of
 * magnitude (a 5-point arrow next to a 30000-point gun): linear quarters
 * would collapse every meaningful cap into the first tier.</p>
 *
 * <p>Pure int math on {@link PriceRange} values — no Minecraft or platform
 * imports — so the server (which publishes the result through
 * {@link PriceTableRegistry}) and the platform screens share one algorithm
 * and can never disagree about which caps are legal.</p>
 */
public final class QuoteCaps {

    /** Selector value meaning "no cap" (the legacy {@code -1} sentinel). */
    public static final int UNLIMITED = -1;

    /** Priced tiers shown before the trailing "unlimited" entry. */
    public static final int TIER_COUNT = 4;

    /** No priced tiers: the selector offers only "unlimited" (empty table). */
    public static final int[] NONE = new int[0];

    private QuoteCaps() {
    }

    /** Tiers for the active price table ({@link #TIER_COUNT} priced + unlimited). */
    public static int[] tiers(PriceTable table) {
        if (table == null || table.isEmpty()) {
            return NONE;
        }
        return tiers(table.entries().values(), TIER_COUNT);
    }

    /**
     * Tiers for a collection of price ranges. Unpriced sentinels are ignored;
     * the ladder is built from the highest {@code max} in the collection.
     * The returned array is strictly ascending and free of duplicates, so a
     * degenerate table (a single cheap item) simply yields fewer tiers.
     */
    public static int[] tiers(Collection<PriceRange> prices, int tierCount) {
        if (prices == null || tierCount <= 0) {
            return NONE;
        }
        int max = 0;
        for (PriceRange range : prices) {
            if (range == null || range.isUnpriced()) {
                continue;
            }
            if (range.max() > max) {
                max = range.max();
            }
        }
        return tiersForMax(max, tierCount);
    }

    /**
     * Geometric ladder up to {@code maxPrice}. Tier {@code i} (0-based) sits at
     * {@code maxPrice^((i+1)/tierCount)}, rounded up, with the final tier pinned
     * to {@code maxPrice} itself so the selector always covers the whole table.
     * Duplicates created by rounding are collapsed, which is what makes very
     * small tables degrade gracefully instead of repeating a value.
     *
     * <p>{@code maxPrice <= 0} (empty table / every entry priced 0) returns
     * {@link #NONE} — with no positive price the only meaningful cap is
     * "unlimited".</p>
     */
    public static int[] tiersForMax(int maxPrice, int tierCount) {
        if (maxPrice <= 0 || tierCount <= 0) {
            return NONE;
        }
        TreeSet<Integer> tiers = new TreeSet<>();
        for (int i = 0; i < tierCount; i++) {
            int value;
            if (i == tierCount - 1) {
                value = maxPrice;
            } else {
                double exponent = (i + 1) / (double) tierCount;
                value = (int) Math.ceil(Math.pow(maxPrice, exponent));
                if (value < 1) {
                    value = 1;
                }
                if (value > maxPrice) {
                    value = maxPrice;
                }
            }
            tiers.add(value);
        }
        // The pinned top tier can still be missing when ceil() overshot into
        // maxPrice early and a later tier rounded below it; the set keeps the
        // ladder sorted, so ensure the top is present.
        tiers.add(maxPrice);
        int[] out = new int[tiers.size()];
        int i = 0;
        for (int tier : tiers) {
            out[i++] = tier;
        }
        return out;
    }

    /** True when {@code cap} is the unlimited sentinel or one of {@code tiers}. */
    public static boolean isAllowed(int cap, int[] tiers) {
        if (cap == UNLIMITED) {
            return true;
        }
        if (tiers == null) {
            return false;
        }
        for (int tier : tiers) {
            if (tier == cap) {
                return true;
            }
        }
        return false;
    }

    /**
     * Display fallback: the cap to show when a stored value is no longer part
     * of the current ladder (price table edited between sessions). Keeps an
     * already-valid value untouched.
     */
    public static int normalize(int cap, int[] tiers) {
        return isAllowed(cap, tiers) ? cap : UNLIMITED;
    }
}
